### ISSUE TITLE
baseBoundary not being automatically set from Content-Type header

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#1008]
If the following headers object is passed to sendMail method:

```sh
headers:
   { 'content-type':
      'multipart/alternative; boundary=--_NmP-f4bbc6a218387c5d-Part_1',
     'mime-version': '1.0' },
```

Then I would think that `baseBoundary` would get set to `--_NmP-f4bbc6a218387c5d-Part_1` by default.

However it does not, so I would have to set it myself and also set the prefix too?

Related:
- https://github.com/niftylettuce/forward-email/issues/85
- https://github.com/nodemailer/nodemailer/issues/495
- https://github.com/nodemailer/nodemailer/blob/4b6942206277abaedddcf35561539812587fe141/lib/mime-node/index.js#L40-L44

**Comment by niftylettuce** [comment]
Update comment and title.

**Comment by niftylettuce** [comment]
I think the same goes for Content-Transfer-Encoding header not setting `textEncoding` option as well.

**Comment by andris9** [comment]
@niftylettuce  You can not set structural headers like `content-type` in Nodemailer. The actual structure of the message is decided by Nodemailer depending on the input values. For example you try to set `multipart/alternative` but Nodemailer might decide to go with `multipart/mixed` with nested `multipart/alternative`. Or you might want to set `multipart/mixed` but Nodemailer goes with `multipart/alternative` with html part and an attachment nested in `multipart/related` etc. Actual boundaries use ordered numbering (`baseBoundary` + appended part number).

Regarding https://github.com/niftylettuce/forward-email/issues/85 there are two issues:

* Mailparser does not support ISO-2022-JP out of the box as [iconv-lite](https://www.npmjs.com/package/iconv-lite) is not able to decode it. Messages using ISO-2022-JP end up in a broken state.

For a quick fix you could switch over to using [node-iconv](https://www.npmjs.com/package/iconv) that has larger supported set of charsets (but requires compiling) like this:

```
const MailParser = require('mailparser').MailParser;
const Iconv = require('iconv').Iconv;
let parser = new MailParser({ Iconv });
```

* Using Mailparser for preprocessing forwarded messages is not the best approach as data loss can occur. Current ISO-2022-JP handling is one example but it also might break embedded message/rfc822 content, calendar events etc.

You should use a different approach where you do not actually parse the message but keep it as it is. Nodemailer is able to use precompiled messages by the `raw` property. Instead of Mailparser you could use the underlying Mailsplit module that does not try to force the email into some specific structure.

[Here's an example](https://gist.github.com/andris9/94e73deef71640322c422b27cded5add) of using Mailsplit and Nodemailer to achieve similar functionality as your forwarder has without breaking the email. The example script processes only specific message headers, keeping everything else as is. This way it does not matter how the email is structured or what kind of character set it uses.

**Comment by niftylettuce** [comment]
ty

**Comment by niftylettuce** [comment]
@andris9 I think your example is missing some usage, see https://gist.github.com/andris9/94e73deef71640322c422b27cded5add#gistcomment-2908357
