### ISSUE TITLE
SMTP server closes connection

### ISSUE THREAD

**Issue by mayrbenjamin92** [nodemailer/nodemailer#1059]
We are using nodemailer in our product and are really happy with its current feature-set, but we have discovered a problem recently. We are using the connection pool approach to send emails from within our software product to a configurable SMTP server. Once everything was configured, emails can be sent in a reliable way, until the SMTP server closes the connection from their side!

We checked and found issues where e.g. the SMTP server from office365 would close the connection from their site if they encounter a huge number of connections to their servers. Nodemailer currently does not really have an option or functionality to check. I am right? We have the "verify" method, but it creates a brand new connection and is meant for checking whether the connection options are correct - but it's not really what we want to try!

One of my ideas was, that we could have a look at the underlying TCP socket and check whether we are still connected.

Any thoughts?

**Comment by andris9** [comment]
Nodemailer pool creates connections lazily, eg. only when it actually needs one. If a server closes a connection (usually because of timeouts) then Nodemailer does not reopen the connection until there is another email to be delivered. So normally when you have currently no emails to send then Nodemailer has 0 connections to the server and there’s nothing to check for.
