### ISSUE TITLE
Postinstall takes 4+ seconds

### ISSUE THREAD

**Issue by AdriVanHoudt** [nodemailer/nodemailer#1158]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

Hi,

I don't mind the post install script at all. I actually like seeing what other interesting projects you are working on.
The thing I don't like is the deliberate 'sleep' in the script.
This causes unnecessary slowdowns in development and deploys.
Would it be possible to revise this and preferably remove the slowdown?

**Comment by andris9** [comment]
The same has been asked several times, so I made a sponsorship tier to remove it: https://github.com/sponsors/andris9

**Comment by AdriVanHoudt** [comment]
I see, why not mention this in the post install script? I didn't know this was a thing.

**Comment by AdriVanHoudt** [comment]
I brought this up internally and Salesflare is now a sponsor through one of the founders ✨ (@JeroenCorthout)
I hope you reach your goal soon.
Mentioning the sponsorship goal in the readme/postinstall script might help!

**Comment by andris9** [comment]
@AdriVanHoudt awesome, thanks! And I will add a note to the postinstall script next release

**Comment by ofbeaton** [comment]
In my opinion, this sleep(4) should be mentioned in the `readme` and in the postinstall script output itself. Otherwise developers have to do profiling/debugging to figure out where/how the install degradation is coming from.

Devs are free to use any package they want, but it would help them make informed decisions if they know what they are getting / what tradeoffs they are making.

Of course as a complete aside, I really hope we as a community find a way to financial support developers in a way that works, especially sub-dependencies. This method while likely raising more awareness and conversation, in my opinion is unlikely to be that long-term solution. My brand new graphql hobby project has 1424 packages including sub-dependencies, if they all added a 4 second delay, my install would take 1.5 hours. 63 packages use the `funding` flag and if only they added a delay, it would already add 4.2 minutes to every install.
