### ISSUE TITLE
Feature Request: Dns.Lookup instead of dns.resolve.

### ISSUE THREAD

**Issue by ccebinger** [nodemailer/nodemailer#1283]
I would like a Option which uses Dns.Lookup instead of dns.resolve because I don't use a DNS server and want to use /etc/hosts.
Best,
ccebinger

**Comment by andris9** [comment]
Nodemailer allows you to provide an IP address instead of hostname, so you can handle the lookups yourself if needed.

**Comment by phiresky** [comment]
Using dns.lookup apparently means that the /etc/hosts file is ignored, which caused a very confusing bug for us where when we switched the DNS server to `1.1.1.1`, nodemailer suddenly stopped working. The reason is that some DNS resolvers resolve `localhost` to `127.0.0.1`, but some don't.

We don't even use any fancy custom hostnames in /etc/hosts. In my opinion `localhost` should always be resolved with `/etc/hosts` instead of whatever a remote DNS server returns. I have no idea why node even has multiple ways of resolving host queries, but so far nodemailer is the only thing where we stumbled upon this issue.

**Comment by KyleMaas** [comment]
This is still very much a problem.  Yes, you can pass in an IP address, but that means that it won't be able to validate the certificate name so you get errors for that.  We had to forcibly DNAT all outbound traffic to a certain port on our servers to work around this problem with DNS resolution.  Not just something which can be easily ignored.

**Comment by andris9** [comment]
@KyleMaas this issue is [covered in the docs](https://www.nodemailer.com/smtp/)

> Hostnames for the host field are resolved using dns.resolve(). If you are using a non-resolvable hostname (eg. something listed in _/etc/hosts_ or you are using different resolver for your Node apps), then provide the IP address of the SMTP server as host and use the actual hostname in the `tls.servername` parameter. This way, no hostname resolving is attempted, but TLS validation still works.
