### ISSUE TITLE
Unable to override service presets in SMTP transport

### ISSUE THREAD

**Issue by daniellockyer** [nodemailer/nodemailer#1327]
Hey! 👋🏻 

I've just updated Nodemailer in Ghost and noticed that I'm unable to override service presets in the SMTP transport, such as `host`.

It's common for our users to do something like:

```
... //mail config
    "options": {
        "service": "SES",
        "host": "some_other_endpoint_than_the_preset_one_for_SES"
    }
...
```

I'd expect this to use the [SES](https://github.com/nodemailer/nodemailer/blob/04e6c2c402a3f2317ce0074d7939c5cc87d2174d/lib/well-known/services.json#L205-L209) service config and then use the `host` url I provided.

I'm aware `SES-*` services exist but let's imagine it's some other endpoint like the one for the sandbox zone `us-east-2`. For development, just adding/changing the `host` makes it a lot easier too.

I believe it's due to the ordering of https://github.com/nodemailer/nodemailer/blob/master/lib/smtp-transport/index.js#L39-L44, but I want to check what was intended and express what I expected to happen.

**Comment by andris9** [comment]
`service` option is deprecated. You can still use it but the documentation does not list it anymore. In general I'd advise you to not provide email configuration directly to Nodemailer but use a preprocessing step of some kind, so that you would take the configuration from the config file and then generate Nodemailer specific configuration out of it.

Regarding the question, yes, service options override other options. It's been like this for too long for now to reverse it.
