### ISSUE TITLE
Mail sender

### ISSUE THREAD

**Issue by djordjepetrovicdjordje** [nodemailer/nodemailer#1403]
Hi,

I'm trying to send an email with address object. I saw the doc here https://nodemailer.com/message/addresses/

{
    name: 'Майлер, Ноде',
    address: 'foobar@example.com'
}

The sender name is Майлер, Ноде and sender address is foobar@example.com and it is all ok... In my inbox I can see the email from Майлер, Ноде

If I change the address and try to send from foo.bar@example.com (foo.bar with dot)

{
    name: 'Майлер, Ноде',
    address: 'foo.bar@example.com'
}

the sender name will not be displayed... In my inbox I see the email from foo.bar@example.com not from Майлер, Ноде

If I try with foo-bar@example.com
{
    name: 'Майлер, Ноде',
    address: 'foo-bar@example.com'
}
everything is ok and I see email in my inbox from Майлер, Ноде

Can you please check this option if address contains dots?

**Comment by WillianAgostini** [comment]
Hi @djordjepetrovicdjordje,

You can easily work around this by adding a quote on the full name.

I can reproduce this with test on 7cfc644bb9ad848343222ef04bd9b92809c5c435.
It happens when I send email without quotes, like `Ноде Майлер <bar@example.com>`.
If I send it with quotes it's Ok. `"Ноде Майлер" <bar@example.com>`.

So there are the questions.
I see we can use a formated name without quotes to 1 email only, like this line https://github.com/WillianAgostini/nodemailer/blob/7cfc644bb9ad848343222ef04bd9b92809c5c435/test/addressparser/addressparser-test.js#L39

Because I create this test error to show why must be 1 test only https://github.com/WillianAgostini/nodemailer/blob/7cfc644bb9ad848343222ef04bd9b92809c5c435/test/addressparser/addressparser-test.js#L330

**Comment by djordjepetrovicdjordje** [comment]
Hi @WillianAgostini,

Thanks for your response...

That's fine, but it wasn't the issue I reported...

I added 3 examples

- name is the same, "Ноде, Майлер" for all of them
- address is changed

If I use address: '**foobar**@example.com' or address: '**foo-bar**@example.com' everything is ok and I can see the name (Ноде, Майлер) as a sender

The problem is when I set the address: '**foo.bar**@example.com'... So if I set the address with dot - foo.bar - I can't see the name (Ноде, Майлер) as a sender

**Comment by andris9** [comment]
You can't use random `from` addresses, only your account address.
