### ISSUE TITLE
Receivers do not receive the mail

### ISSUE THREAD

**Issue by devzui** [nodemailer/nodemailer#1439]
Hello, I'm currently struggling with how Nodemailer works. 
I have used the example code for NodeJS but for some reason I do not receive the email.
Is there something else I have to check or did I miss something. Sorry for the issue if it was unneccessary.

```js
// Generate SMTP service account from ethereal.email
nodemailer.createTestAccount((err, account) => {
    if (err) {
        console.error('Failed to create a testing account. ' + err.message);
        return process.exit(1);
    }

    console.log('Credentials obtained, sending message...');

    // Create a SMTP transporter object
    let transporter = nodemailer.createTransport({
        host: account.smtp.host,
        port: account.smtp.port,
        secure: account.smtp.secure,
        auth: {
            user: account.user,
            pass: account.pass
        }
    });

    // Message object
    let message = {
        from: 'Fred <fred@ethereal.email>',
        to: 'Felix<realdeval12@gmail.com>',
        subject: 'Nodemailer is unicode friendly ✔',
        text: 'Hello to myself!',
        html: '<p><b>Hello</b> to myself!</p>'
    };

    transporter.sendMail(message, (err, info) => {
        if (err) {
            console.log('Error occurred. ' + err.message);
            return process.exit(1);
        }

        console.log('Message sent: %s', info.messageId);
        // Preview only available when sending through an Ethereal account
        console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
    });
});

**Comment by topbestcoder** [comment]
It looks like the emails have been all deleted... We can create a new one but I have not tested if the emails are received....
And the status page cannot be displayed because of an invalid certificate.
I sent an email to the admin but he still not replied...

**Comment by darion6** [comment]
I'm having a similar problem how did you resolve it...I don't receive any mail

**Comment by topbestcoder** [comment]
I sent an email to the admin. Here is his reply :
1 : When he has no more place on his server, he deletes all of them and all the email addresses... Usually, it's done more often then this time...
2 : The status page is no more available because he used a free web service which is no more free...

Maybe, he could have written on his site that emails & email addresses are deleted when he has no more place... No communication but it's free ;)

Use these email addresses ONLY for test, not for registering anywhere...

**Comment by topbestcoder** [comment]
A copy of his email:

The server ran out of disk space. This has not happened for a while, and that's why the accounts were usable for a long time. Ethereal.email is a free service. I pay for the server costs personally and can't afford bigger servers, so in order to keep the service free for everybody, such freeing of resources happen from time to time.
 
The status page used to be a free tier offering from a status page service provider. They stopped offering the free tier, and thus the status page does not work anymore. I have not found a similar alternative yet.

Best regards,
Andris Reinman
Ethereal.email

**Comment by darion6** [comment]
He's no more running the service

**Comment by topbestcoder** [comment]
No. I have created a new account and all is ok.

**Comment by darion6** [comment]
ok thnx
