### ISSUE TITLE
[bug] logger option does not function properly (shared logger overrides any existing logger passed; this is not best practice)

### ISSUE THREAD

**Issue by titanism** [nodemailer/nodemailer#1489]
Nodemailer supports a `logger` option, however this option actually does not function the way one would think.

When you pass a custom logger, it gets transformed into a bunyan version, and is not the same logger method.

As you can see below,  the object returned is `response`, which is a manipulated version of the `logger` passed that we want to use:

https://github.com/nodemailer/nodemailer/blob/e091992f9f88de09218c103bccb98686ea4105aa/lib/shared/index.js#L367-L402

Specifically you are making it a bunyan compatible version, regardless of whether or not the user wants to use such a version.

Also, there is no workaround for this, even outside of nodemailer, as `nodemailer.createTransport` will use this shared logger implementation, including on the first debug log &ndash; as you can see here: <https://github.com/nodemailer/nodemailer/blob/368f545753b92f1954c0c98c5f151ac38afb1f0d/lib/mailer/index.js#L47-L57>

**Comment by andris9** [comment]
Yes, it definitely is not a best practice to modify provided objects, but this behavior is intentional, and it took years to come up with it. Hundreds of thousands of developers use Nodemailer, and there are a gazillion logging implementations out there. Most people just insert some random logging implementation to Nodemailer and expect things to work without throwing any exceptions. It is impossible to have built-in support for each of these, and the current approach is the one that suited the most. 

The correct way to use logging is to use wrappers. For example, [see here](https://github.com/postalsys/emailengine/blob/85e0cdc7d487012d2e48d83fd6cf6d8c5944a19d/lib/connection.js#L1750-L1763) for using [pino](https://github.com/pinojs/pino) with Nodemailer.
