### ISSUE TITLE
Greeting never received for existing proxy connection

### ISSUE THREAD

**Issue by marikaner** [nodemailer/nodemailer#1684]
I want to use nodemailer through a proxy and currently I receive the error: "Greeting never received". After debugging this quite in-depth I think this is a bug in nodemailer.

How I try to send mails using nodemailer:

1. I create a proxy connection using the socks library (`SocksClient.createConnection(...)`). This already sets up a connection, sends an established event with 220. 
3. Then I create a transport with nodemailer, that recognizes that there is already a connection. Internally this calls `_onConnect()`, which in turn waits for a greeting. However, the greeting already fired before and won't be sent again, so that this step already fails with "Greeting never received".
I also tried using a custom proxy handler as described [here](https://nodemailer.com/smtp/proxies/#3-using-a-custom-proxy-handler) with the same result.

I believe when there is an existing connection nodemailer should not wait for a greeting, but assume the connection is there already.

**Comment by marikaner** [comment]
@andris9 

We found a workaround for this by just resending the greeting message manually. Of course I would prefer for nodemailer to do this correctly instead of resending this message as this could be error prone.

**Comment by andris9** [comment]
I am not sure how this is an issue with Nodemailer if the 220 response processing happens outside Nodemailer 🤔 Nodemailer handles the entire protocol chain, and if something is missing, then it obviously would not work.

**Comment by marikaner** [comment]
Hey @andris9, this is exactly the problem - nodemailer is not handling this correctly. I tried to use the custom proxy handler as described in the documentation: https://nodemailer.com/smtp/proxies/#3-using-a-custom-proxy-handler. We have a socks proxy with slightly more complicated authentication and other information on it. According to the documentation in this handler the socket is connected - which sends out the 220 message.
Nodemailer only listens to this message after this was sent. Seems like a bug to me, please reopen.

**Comment by andris9** [comment]
If the 220 response was already consumed from the TCP socket before Nodemailer was able to read it, then you are doing something wrong. Bytes do not magically disappear from the TCP socket, something must be consuming/reading it.

**Comment by marikaner** [comment]
@andris9 this is not how events work. Let me describe the issue step by step:

1. We setup a transport with a custom proxy handler as described in [here](https://nodemailer.com/smtp/proxies/#3-using-a-custom-proxy-handler) using the socks lib:
```
transporter.set('proxy_handler_socks5', async (proxy, options, callback) => {
  callBack(null, { connection: await SocksClient.createConnection(...) };
});
```
2. Internally the socks library then connects the client and emits a `data` event with the greeting message, see [here](https://github.com/JoshGlazebrook/socks/blob/a2a06d9967edfaa317e6d20d33963b95a3e654e3/src/client/socksclient.ts#L349-L359).
3. Then, we try to send the mail with `transporter.sendMail()`. Nodemailer tries to connect and because there is already a connection, it [goes to the `_onConnect()` handler immediately](https://github.com/nodemailer/nodemailer/blob/81de9ebaeb84d5dd87a16707fd236d2671cb6cc6/lib/smtp-connection/index.js#L257).
4. In the `_onConnect()` handler, nodemailer then starts listening to the `data` event, but the initial greeting event was already sent out when creating the transport, so it is too late to receive it at this point.
5. Ultimately nodemailer then fails with `Greeting never received` for now obvious reasons [here](https://github.com/nodemailer/nodemailer/blob/81de9ebaeb84d5dd87a16707fd236d2671cb6cc6/lib/smtp-connection/index.js#L727).

With my current understanding of how nodemailer and the socks proxy operate it is obvious to me that nodemailer has a bug, where it waits for an event that was emitted before nodemailer starts listening to it. We do not process the response in any way and let nodemailer + socks do their thing.

Please explain to me how you think this is supposed to work, in case you think my understanding is wrong.

**Comment by marikaner** [comment]
@andris9 Could you please reopen this issue. I am quite sure that this is an actual bug in nodemailer as described above.

**Comment by andris9** [comment]
I still believe that this is not a bug on Nodemailer. If you open a proxy socket and receive any data from it before passing the socket to Nodemailer, then the correct behavior is to cache that data you received from the socket and later re-write it to the socket so that Nodemailer would receive it. If you just randomly lose bytes, then it will break the protocol handling.

**Comment by marikaner** [comment]
But then it is incorrectly documented.

**Comment by andris9** [comment]
I don't see where the issue is. Just to be sure, I opened the [documentation page](https://nodemailer.com/smtp/proxies/), followed the examples there to create a Nodemailer connection with a SOCKS proxy, sent an email using that script, and everything worked fine. The greeting was not lost. See the code here: https://gist.github.com/andris9/9f6bf1d5443233d98d47da8fb6573ef8 I really don't see where you are losing the greeting bytes 🤷‍♂️

**Comment by ZhongpinWang** [comment]
@andris9 Now we can narrow the issue down to port `587` only. Port `465` works fine which you also tested by following the documentation page.

First, I can explain why it works for port `465`. We create a socket first with the [socks client ](https://github.com/JoshGlazebrook/socks), which is essentially using `Socket` from `net`. While creating the socket, we don't receive any greeting message since port 465 requires TLS, which [will be upgraded by nodemailer](https://github.com/nodemailer/nodemailer/blob/e70b9c18bd4ba14d500197fa1614ed37f5536446/lib/smtp-connection/index.js#L906). So we give this connected plain text socket to nodemailer. It upgrades the connection and [creates on data handler at the same time](https://github.com/nodemailer/nodemailer/blob/e70b9c18bd4ba14d500197fa1614ed37f5536446/lib/smtp-connection/index.js#L935) when doing `tls.connect()`. This on data handler is the key to receive the greeting message and call actions further. This is why, port `465` works. I assume you know this better than me. But just to make my explanation complete. 😄

But for port `587` it will **NOT** work. `587` means plain text at the very beginning and then STARTTLS. When creating socket before nodemailer kicking in, the greeting message has already been sent once socket was connected. The remote smtp server sends the greeting message bytes through the socket and WE [HAVE TO CONSUME IT](https://github.com/JoshGlazebrook/socks/blob/a2a06d9967edfaa317e6d20d33963b95a3e654e3/src/client/socksclient.ts#L331) via an on data handler, otherwise according to official Node.js documentation for `Net`, I quote, "[the data will be lost if there is no listener when a Socket emits a 'data' event.](https://nodejs.org/api/net.html#event-data)". This gives us no choice, but to implement a workaround to store the greeting message and re-emit it with retry after we create Transport with nodemailer. It means that at the moment of the socket creation and the receiving of the greeting message, not even a single line of nodemailer's code has been executed yet, meaning NO on data handler registered, and later NO further process action possible.

So nodemailer's assumption that with port 587 and a connected socket, there will be a greeting message for nodemailer to receive is wrong. There must be another way for nodemailer to check if smtp server is available, e.g., by sending something and wait for some response instead of depending on the greeting message.

I hope the explanation above make the issue more clear. And thanks for reading through it. We would really appreciate this issue to be re-open and resolved.

**Comment by andris9** [comment]
Nodemailer operates correctly. You can test it out using this updated gist: https://gist.github.com/andris9/731f214babc664f7e09229171296a6aa

From your description, I understand that you are using the legacy "data" event for reading data from a socket. Instead, you should be using "readable". Unlike "data", there is no data loss with "readable".
