### ISSUE TITLE
smtp without service failing

### ISSUE THREAD

**Issue by gabeno** [nodemailer/nodemailer#230]
When I try to send email following without service example, I get the following error:

```
Error: Authentication required, invalid details provided
```

However, I can connect to the gmail smtp server (implemented as suggested [here](https://github.com/andris9/Nodemailer/issues/206)) and get success with the same `config` object:

```
var config = {
  host: "smtp.gmail.com",
  port: 465,
  secureConnection: true,
  requiresAuth: true,
  auth: {
    user: "xxx",
    pass: "xxx
  }
};
```

What could be the issue?

**EDIT** 

After digging around trying to find the problem, I noticed checking connection using [this suggestion](https://github.com/andris9/Nodemailer/issues/206) now also brings error, see stack trace:

```
AuthError: Invalid login - 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8 http://support.google.com/mail/bin/answer.py?answer=14257 v10sm72659392qeh.14 - gsmtp
  at SMTPClient._actionAUTHComplete (/home/gabriel/projects-node/brim/node_modules/simplesmtp/lib/client.js:858:23)
  at SMTPClient._onData (/home/gabriel/projects-node/brim/node_modules/simplesmtp/lib/client.js:335:29)
```

**Comment by dimoreira** [comment]
@gabeno I'm having this issue till today. Can you please elaborate on your solution?

**Comment by cleechtech** [comment]
yeah please reopen, getting the same error also

**Comment by suvarna123addanki** [comment]
hello @gabeno  i am having this issue please elobrate the answe

**Comment by ibidpayfazz** [comment]
maybe this will help, some reference have different params.
in node mailer documentation using "secureConnection" but in ghost documentation it use "secure",  it may diffrent in other cases.

for Error: Authentication required, invalid details provided , the problem is one of parameter that you provide it's not found by the system probably you use different params.

for example in my case :
  auth: {
    user: "xxx",
    password: "xxx
  }

it should be
  auth: {
    user: "xxx",
    pass: "xxx
  }

other cases may different, lest find out deep, I give my 4 hours to find this btw
