### ISSUE TITLE
Specified from address never used

### ISSUE THREAD

**Issue by georgemandis** [nodemailer/nodemailer#240]
When I'm specifying the `from` message field and passing it to sendMail I'm formatting it like the example:

`user: "Jane Doe <me@example.com>"`

The email arrives just fine, and the Jane Doe part appears correctly, but the from address never shows me@example.com; it shows the email address I authenticated the transport with. FWIW, I'm using a Google Apps email address. I've also setup the address I'm trying to use here as an alias within Google Apps, thinking that may have been an issue. When I examine the headers in the received email however I see no sign at all of me@example.com.

My goal here is to use a generic email address for automated purposes — something like app@example.com — but change it so it appears to come from billing@example.com, account@example.com, etc. Right now I can change the sender name to 'Billing', 'Accounts', etc., but the email address will still always show as app@example.com.

Is this a specific issue to Gmail or Google Apps?

**Comment by holographix** [comment]
Sorry to revamp this, but I got the exact same issue..
I'm trying to send an email using my gmail account as smtp and the email that I receive by the other side has the name I gave i n configuration, but the email address is mine instead of the alias that I used..


here it comes my conf


		var transporter = nodemailer.createTransport({
		    service: 'gmail',
		    auth: {
		        user: 'mygmailaddr@gmail.com',
		        pass: 'mygmailpass'
		    }
		});

		var mailOptions = {
		    from: 'Client support <support@anotherdomain.com>', // sender address
		    to: rcpt, // list of receivers
		    subject: subj, // Subject line
		    html: html_str // html body
		};

		transporter.sendMail(mailOptions, function(error, info) {
		    if(error) 	console.log(error);
		    else 		console.log('Message sent: ' + info.response);
		});

voila'.
At first I tought that the problem was related to the fact that I was trying to send test email to mygmailaddr@gmail.com but afterwards I made an attemp on a total different hotmail account and the result is always the same: 
The email that I get is from "Client Support" but the address is mygmailaddr@gmail.com instead of support@anotherdomain.com.

any suggestion to get outa this would be more that appreciated!
thx!

**Comment by andris9** [comment]
If you try to send email through Gmail, then Gmail overwrites the from address to always be the one that was used for authentication. If you want to use `support@anotherdomain.com` address as the sender then you should either log in as this user (assuming that this is a Google Apps account) or use another service that does not do such rewriting, eg. MailGun, SendGrid ets.

**Comment by holographix** [comment]
hey cool, thx! I'll try that and I'll let u know it goes!
thx!

**Comment by reachdevelopers** [comment]
I am having the same issue and can't figure out hot add "from" = the sender email

**Comment by Berci-Ionut** [comment]
Hi. Having the same issue. I understand the google rewrite, so I also tried to sent it to yahoo, but I got the same result.

**Comment by piavgh** [comment]
> Hi. Having the same issue. I understand the google rewrite, so I also tried to sent it to yahoo, but I got the same result.

If you use service: 'gmail', it will always use the email inside auth.user because that's the email you can control.

If you can use any email that you don't control (for example trump@gmail.com), you will make the recipients very confused
