### ISSUE TITLE
NodeMailer error: SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by akreitals** [nodemailer/nodemailer#310]
Whether I use a simple Gmail service or a custom SMTP configuration I always get a response with `[Error: SELF_SIGNED_CERT_IN_CHAIN]`.

Using using Node v0.10.30 and NodeMailer v1.1.1. Incidentally this is not an issue using the older v0.5.15 on another project on the same server.

Same response if I set the `ignoreTLS` option to true. Any ideas?

**Comment by romuloctba** [comment]
nevertheless trying to connect without certificate results in this:
lease log in via your web browser and then try again.\n534-5.7.14 Learn more at\n534 5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754 d32sm8306558qga.12 - gsmtp","responseCode":534}

**Comment by andris9** [comment]
@romuloctba If you are seeing this error from Gmail, then your login is caught by Gmail robot-detection heuristics. See [this notice](https://github.com/andris9/Nodemailer#using-gmail) about using Gmail with Nodemailer (or any other mailer).

**Comment by SebastianOsuna** [comment]
@romuloctba I got the same error when trying to send mails through a business gmail account. The problem is gmail's security level. I was trying to user username/password for authentication, but gmail's seems to require OAuth2 unless you are willing to lower your account's security.

I ended up moving to Amazon SES.
