### ISSUE TITLE
Notes transporter with nodemailer

### ISSUE THREAD

**Issue by brahdian** [nodemailer/nodemailer#523]
Hi Andris,
 I'm a new in nodejs and looking for a module which can send emails from Node.js Application.
However the problem is that i want to use NOTES routing instead of using SMTP or POP3 or any other protocol. so I wonder if there is a way to send emails using nodemailer and NOTES routing. and if not can you guide me creating a NOTES transporter for nodemailer.

Thank you

**Comment by andris9** [comment]
You mean like Lotus Notes NRPC protocol? I think it is proprietary, I have no idea how it works and I can't test it as I do not have access to any Lotus software. 

If you are willing to implement such tranport yourself then look into nodemailer-pickup for an example, this tranport stores message to a file instead of sending it to anywhere, so it gives a quick overview how transports work for Nodemailer https://github.com/andris9/nodemailer-pickup-transport
