### ISSUE TITLE
attachment headers being ignored/overridden

### ISSUE THREAD

**Issue by schme16** [nodemailer/nodemailer#559]
I'm trying to send an attachment (.ics file) and cannot set the `Content-Transfer-Encoding` to `base64` (when I do it decoded my `base64` text and changes its `Content-Transfer-Encoding` to `quoted-printable`)

I also do not seem to be able (either through the property or the headers) to set the `Content-Type` to `text/calendar; charset="utf-8"; method=REQUEST`

I should also mention that I'm using the attachement->content, as opposed to the attachment->path to supply the data for the attachment

Any ideas?

**Comment by andris9** [comment]
All text/* alternatives are encoded to quoted-printable (unless the content is 7bit) by default. Is there a problem with using quoted-printable instead of base64? I can't check how Outlook actually treats it but Google Calendar seems also to use quoted-printable for the calendar events. To get the needed content-type header, you could add the alternative like this:

    alternatives: [{
        contentType: 'text/calendar; charset=UTF-8; method=REQUEST',
        content: calendarContentString
    }]

**Comment by andris9** [comment]
Nodemailer v2.2 beta now supports iCalendar events out of the box as there's a new option `icalEvent` for that. See an example [here](https://github.com/nodemailer/nodemailer/blob/v2.2/examples/ical-event.js#L31-L36).

This is still beta, so you would have to install this version of Nodemailer from the beta channel (`npm install nodemailer@beta`) or wait until stable is released.

**Comment by schme16** [comment]
@andris9: awesome, I'll grab that branch and see if it outlook accepts the calendar attachment correctly!

**Comment by schme16** [comment]
Beta branch works perfectly, cheers!
