### ISSUE TITLE
250 returned no matter what

### ISSUE THREAD

**Issue by wgormley** [nodemailer/nodemailer#602]
i am having an issue, would love some input. no matter what postfix is returning, nodemailer is always returning a 250.

from mail.log
`postfix/smtp[1432]: 0CA4412040B: to=<wwwwwww@an34er.com>, relay=none, delay=0.44, delays=0.1/0.01/0.33/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=an34er.com type=AAAA: Host not found)`

returned from nodemailer

```
{ accepted: [ 'wwwwwww@an34er.com' ],
  rejected: [],
  response: '250 2.0.0 Ok: queued as 0CA4412040B',
  envelope: { from: 'noreply@XXXXXXX.com', to: [ 'wwwwwww@an34er.com' ] },
  messageId: '1461103054033-fb280098-1bc4f33e-cb51a4c3@XXXXXXX.com' }
```

1) nodemailer@2.3.0
2) v4.4.2
3) Ubuntu (Amazon ec2)

**Comment by andris9** [comment]
This is because Postfix accepts and queues the message for delivery and the actual sending happens way after Nodemailer has already got its success response from Postfix. This is completely normal and part of how message delivery works – messages go through several MTA servers and each of these can reject the message. If you want to know a message was bounced you should either use a [VERP](https://en.wikipedia.org/wiki/Variable_envelope_return_path) address and catch messages sent to this address or alternatively grep the Postfix logs. Alternatively you could use a service like SendGrid or Mailgun etc. that handles bounces instead of you.

**Comment by wgormley** [comment]
great, thank you @andris9

**Comment by AliKazim7** [comment]
Hi, i received 
response: 'Messages queued for delivery' 
waited for 5 mins still didnt received mail
