### ISSUE TITLE
Sending bulk emails

### ISSUE THREAD

**Issue by killmenot** [nodemailer/nodemailer#616]
Hi @andris9,

What are you thoughts / ideas about sending batch mails (optional) support for some transporters? 

For example, PostMark supports [Send batch emails](http://developer.postmarkapp.com/developer-send-api.html) and I'd like to implement it in [nodemailer-postmark-transporter](https://github.com/killmenot/nodemailer-postmark-transport) (I believe other APIs supports bulk sending too) but I found that I cannot process mails like it does in [sendMail](https://github.com/nodemailer/nodemailer/blob/master/lib/nodemailer.js#L226)

Of course, I can ignore this processing and do something like that in my module

```js
function MyMailerModule(options) {
    this.transporter = nodemailer.createTransport(transport(transport_options));
}

MyMailerModule.prototype.sendBatch = function (mails, callback) {
    this.transporter.transporter.sendBatch(mails, function (err, info) {
        
    });
};
```
but it works incorrectly in situations when I configure plugins, like html-to-text or others because a big part of data processing is missed.

I adapt my module to call private methods of NodeMailer (like `_processPlugins `) but I do not like this idea.

The idea is the following:
1. Implement a new public method `sendBatchMails` that accepts array of mails data in nodemailer format and callback
2. Introduce a new boolean property for NodeMailer transport. Let's call it `bulk` for now (by default `false`). Transports must set it to `true` if they support sending bulk emails.
3. `sendBatchMails` checks `bulk` property and  returns error if transporter does not support bulk feature
4. Extract a new private method from `sendMail` that process mail data to use it in both `sendMail` and  `sendBatchMails`

Any feedback is appreciated

**Comment by andris9** [comment]
Sorry for the delay. I have wanted to add something like this for a long time but have never find a solution I would actually like. The core of the problem is that Nodemailer was initially meant for sending a single message at a time and at by now it is too difficult to change this behavior. I think that sending bulk should be something custom like your example implementation or some kind of a wrapper around Nodemailer but not a built-in feature as it would make things even more complex than they are today.
