### ISSUE TITLE
Send attachment without CID

### ISSUE THREAD

**Issue by ricardopolo** [nodemailer/nodemailer#635]
Just like you allow files whitout filename #605

Can you please allow attachment files without generate a random CID?
Some email clientes think attachments are inline just because they have CID

**Comment by andris9** [comment]
Nodemailer does not set Content-ID values by default, so you would need to provide a `cid` property for the attachment yourself to use it. If there is no `cid` value specified in the attachment properties, then there won't be a `Content-ID` header as well

**Comment by ricardopolo** [comment]
@andris9  you are right, is not in the sender part of my logic. Is in the parsing part (using mailparser).

You generate a CID for attachments in mailparser, when one does not exists.
Something like 9db92ca9b4a1ae88edc2d0c6eff19156@mailparser.

So, when I send that attachment using mailparser it gets a CID that originally does not exists. Any way to detect if it was original in the stream or was generated?

**Comment by andris9** [comment]
You can detect autogenerated content-id values by the "@mailparser"-ending, normal Content-ID values should end with a @FQDN.

**Comment by andris9** [comment]
Actually, I'm not even sure anymore why mailparser auto generates these random Content-ID values as it's not much use if the message body does not link to it. Anyway, it has been like this for years, so I don't want touch it to change the behavior. I've been able to update Nodemailer over the years but mailparser hasn't changed much since 2012, just can't find the time for it even though it probably needs a rewrite of some kind.

**Comment by ricardopolo** [comment]
Thanks @andris9 

Meanwhile I fixed using this

````js
if(new_attachment.cid && new_attachment.cid.endsWith('@mailparser')){
   new_attachment.cid = false;
}
````

But I dont find it particularly safe. Maybe some day someone send a CID with that ending text.
Are you afraid of addding just a new variable to know it the CID was auto generated?


Thanks :)
