### ISSUE TITLE
RabbitMQ Example not working

### ISSUE THREAD

**Issue by samsoft00** [nodemailer/nodemailer#641]
Test RabbitMQ example code you've but not working? the sender.js not delivering message to the smtp server and can't find the bug, kindly help.
```
https://github.com/nodemailer/nodemailer/blob/master/examples/rabbit-queue/sender.js
```
Thanks

**Comment by andris9** [comment]
Just checked and it still works. Follow the instructions in the [README](https://github.com/nodemailer/nodemailer/blob/master/examples/rabbit-queue/README.md)

**Comment by samsoft00** [comment]
@andris9 thanks for your quick response, kindly find the logic below

```
pusher.js

```

**Comment by andris9** [comment]
* **pusher.js** generates random e-mail messages and pushes these to a Queue in RabbitMQ for delivery
  * **sender.js** fetches new messages from the Queue and delivers these using Nodemailer to the test server
  * **server.js** is a test SMTP server that receives messages from the sender.js

So in order to test this example you shoud:

  1. Start a RabbitMQ server that you can use
  2. Edit pusher.js and sender.js and edit the rabbitmq connection string variable `queueHost` to point to your RabbitMQ instance
  3. Start in the following order in separate terminal windows
    1. `node server.js`
    2. `node sender.js`
    3. `node pusher.js`

If you had properly configured the example files then you should see how pusher.js generates new messages and in the server.js window you should see how the server receives these messages

**Comment by samsoft00** [comment]
@andris9 please check the updated codes. Thanks

**Comment by andris9** [comment]
Sorry, I don't provide help debugging custom code. Try to get the current official example working and if it works then continue with that to include it in your own app.

**Comment by samsoft00** [comment]
Thanks for the head up, is working correctly now. Thanks @andris9
