### ISSUE TITLE
When 'from' is '"email@address" <email@address>' it gets changed to '<email@address>'

### ISSUE THREAD

**Issue by miqmago** [nodemailer/nodemailer#654]
1) Nodemailer version you are having problems with 2.5.0
2) Node.js version you are using 4.4.2
3) Your operating system OSX 10.11.6
4) If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

When sending an email with this parameters (see `from`):

```js
const transport = nodemailer.createTransport({
    port: 587,
    host: 'mail.example.com',
    secure: false, // https://github.com/nodemailer/smtp-connection/issues/26
    auth: {
        user: 'user@example.com',
        pass: 'password',
    },
});

transport.sendMail({
    from: '"auto-confirm@example.com" <auto-confirm@example.com>',
    to: 'sender2@gmail.com',
    bcc: 'sender1@example.com',
    subject: 'Test',
    text: 'Hello',
    headers: {
        'X-Laziness-level': 1000,
    },
});
```

The info status output is:

```js
{ accepted: [ 'sender1@example.com', 'sender2@gmail.com' ],
  rejected: [],
  response: '250 2.0.0 Ok: queued as 7CF76409A4',
  envelope: 
   { from: 'auto-confirm@example.com',
     to: [ 'sender1@example.com', 'sender2@gmail.com' ] },
  messageId: '9a33c607-6c96-5937-0a86-db2db213321d@example.com' }
```

And the email in gmail (original email text):

```
...
From: auto-confirm@example.com
...
```

The problem is that Gmail shows the sender like `'auto-confirm'` instead of `'auto-confirm@example.com'`

**Comment by andris9** [comment]
I see your problem but this behavior is going to stay. All email fields go through preprocessing stage where addresses are parsed and normalized and such double-values are dropped as part of the normalization. Fixing this would most probably introduce a lot more unexpected issues and thus I would keep the behavior as is.

**Comment by miqmago** [comment]
Hmm... I also see the reason and it's a pitty (if you see in example Amazon confirmation emails they are sent in the way I said, mostly to make the user know that the email is from Amazon)...

Is there any hack that could be done? Please, could you point me to the file/line that I should modify? Thanks!

**Comment by andris9** [comment]
I think you should be able to skip the parsing step by providing an address object instead of address string, for example like this:

```javascript
transport.sendMail({
    from: {
        name: 'auto-confirm@example.com',
        address: 'auto-confirm@example.com>'
    }
    ...
}
```

**Comment by miqmago** [comment]
Also have to say that I don't really understand where is the problem. In the from field, there is a part which is text and another one that is an email address. If you find something like `"my super text" <myemail@example.com>` there is no confusion that `"my super text"` is the text part of the email (which will be shown in Gmail as the sender) and that `<myemail@example.com>` is the email part.

Isn't it exactly the sam in `"myemail@example.com" <myemail@example.com>`?

**Comment by miqmago** [comment]
Ah! I see now your response! that's an easy solution! Thanks 😄

**Comment by miqmago** [comment]
I've tried with your proposal to provide already parsed address object but it doesn't work.

**Comment by miqmago** [comment]
I've tried to send an email from `"something@example.com" <auto-confirm@example.com>` and it is sent in the right way (Gmail shows `From: "something@example.com" <auto-confirm@example.com>`.

So the only case that seems to fail is when the `name` and the `address` are equal (`"auto-confirm@example.com" <auto-confirm@example.com>`), so it's even more confusing. It seems more like a nodemailer strange behavior than made intentionally (otherwise would be something like "I'm going to correct the programmer because it seems that he has made a mistake" and this is an unusable feature, imo, if the programmer is setting `"auto-confirm@example.com" <auto-confirm@example.com>` is because he wants `from` to be like this, not like `<auto-confirm@example.com>`).

I've been diving inside source code but still could not find where the preprocessing normalization stage occurs.

**Comment by nicholaspretorius** [comment]
Good day, 

I see this topic is closed, but I it seems to be the most relevant issue I could find on the topic. 

I have been testing out the sender name formatting on our company's SMTP server and I am not able to specify the Sender Name as described in the [documentation](https://community.nodemailer.com/address-formatting/) (and in the topic above). I have used the following formats: 

`from: 'Specific Sender Name <examplename@domain.com>'`

`from: '"Specific Sender Name" <examplename@domain.com>'`

`from: {
 name: 'Specific Sender Name',
 address: 'examplename@domain.com'
}`

The above examples will set the from address to 'examplename@domain.com' and the sender name to 'examplename' regardless of the submitted formatting.

Nodemailer v4.4.1
Node v8.9.2
Windows 10 Enterprise 1703
Not using Gmail

Digging into the source, in the file lib/mime-node:856, it looks like _parseAddresses strips out the formatting and populates the 'from' field with only the email address. `envelope.to = list[0].address;` This looks to be by design. 

As a sanity check, I tried explicitly setting the from field with formatting, but this caused the email to fail with an EENVELOPE error. 

This leaves me in doubt about how to achieve sender name formatting since andris9's comment above says: "I _think_ you should be able to skip the parsing step..." (emphasis added)?
