### ISSUE TITLE
System.OutOfMemoryException: Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by thenitai** [nodemailer/nodemailer#713]
Hi,

Getting a lot of these errors here:

```
Error: System.OutOfMemoryException: Array dimensions exceeded supported range.
    at SMTPConnection._formatError (/.../node_modules/smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._actionSMTPStream (/.../node_modules/smtp-connection/lib/smtp-connection.js:1358:30)
    at SMTPConnection.<anonymous> (/.../node_modules/smtp-connection/lib/smtp-connection.js:854:18)
    at SMTPConnection._processResponse (/.../node_modules/smtp-connection/lib/smtp-connection.js:669:16)
    at SMTPConnection._onData (/.../node_modules/smtp-connection/lib/smtp-connection.js:493:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
  code: 'EMESSAGE',
  response: '421 9e5bc00b-c32a-4965-a302-4c5f05b5ba3f Error: System.OutOfMemoryException: Array dimensions exceeded supported range.',
  responseCode: 421,
  command: 'DATA' }

```

Node process has enough memory. Server itself has still 8GB memory free. Also, setting this process with --max-old-space-size=3072

We have a fallback system, i.e. it tries to send the email three times. On the second or third try it works. However, this is a new error and I'm wondering what is going on.

Include the following information with your issue:

1) Nodemailer version you are having problems with (eg. v1.3.7)

2) Node.js version you are using (run `node -v` to see it, eg v5.5.0)
6.9.2
3) Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
Ubuntu 16.04.x
4) If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)
Code we use to send:

```
{
 'host' : _smtp.host,
 'secure' : _smtp.port === '465' ? true : false,
 'port' : _smtp.port,
 'auth' : {
  'user' : _smtp.username,
  'pass' : _smtp.password
 },
 'pool' : true,
 'maxMessages' : 'Infinity',
 'maxConnections' : 5,
 'connectionTimeout' : 60000,
 'greetingTimeout' : 60000,
 'tls' : _smtp.port === '465' ? {
  ciphers : 'SSLv3'
 } : {}
}
```

**Comment by andris9** [comment]
Could you describe or give an example of a message that you try to send and that fails with this error? For example are you using large string values as attachments etc.

**Comment by thenitai** [comment]
Sorry processing over 10k emails a day and this happened 4 times in succession. Since then, I haven't seen it anymore. Also finding that email is rather difficult....

**Comment by andris9** [comment]
In this case I don't think this is directly related to Nodemailer, seems like a general out of memory error instead. 10k messages is not much but if you are using a server instance with low RAM and send messages in larger batches then you might run into memory issues.

Don't pile up too many messages. Eg. instead of for-looping all 10 000 messages at once to Nodemailer wait until previous message is sent or Nodemailer emits 'idle' event before processing the next message.

If you use SMTP and large attachments, then prefer attachments as files (provide filename as the attachment source and not the actual contents nor an open file stream), this delays processing the attachment until this message is actually being sent. If you are using SES etc. without SMTP then this doesn't matter too much as the entire message is read into memory before anything is actually sent.
