### ISSUE TITLE
Change default charset body text to CP1251. Possible?

### ISSUE THREAD

**Issue by GermaN-st** [nodemailer/nodemailer#828]
Hello.
Please tell me. Can I specify that the message text(body) is sent in the encoding CP1251?
And also the header was: "Content-Type":"text/plain; charset=windows-1251"

There is a task, send a letter plain text with the encoding CP1251. Is it possible to do this somehow?

Thanks in advance ;)

**Comment by andris9** [comment]
This is not an option. Nodemailer is optimised for UTF-8 and does not support other charsets.

**Comment by GermaN-st** [comment]
Thanks. It's logical and cool. All have long used utf-8.

**Comment by andris9** [comment]
This is mostly because of JavaScript strings are UTF-8 so outputting UTF-8 is extremely easy while outputting CP1251 would require an encoder. There is no charset encoder in Node built in (there is TextEncoder in browser JavaScript though) so an external module would be needed (plus the encoding step which does not exist currently). Things would be different if a lot of people would prefer to use something else than UTF-8 but for now adding support for other charsets would mean quite a lot of work for relatively small gains.

**Comment by GermaN-st** [comment]
I agree completely. I think there is nothing to it. We just have this exception)
