### ISSUE TITLE
Leaking file descriptors

### ISSUE THREAD

**Issue by sheepa** [nodemailer/nodemailer#902]
Nodemailer is leaking file descriptors, one per mail sent. Identified as "sock        0,6      0t0 1474723070 can't identify protocol" lines in lsof.

Setup
Ubuntu 14.04.5 LTS

Transport configuration
nodemailer.createTransport({
    host: '127.0.0.1',
    port: 25,
    secure: false,
});

On locahost port 25 sendmail MTA is listening. I am creating the transport once and the use transport.sendMail() repeatedly.

**Comment by andris9** [comment]
Could you debug Nodemailer on your system to see what is going on? There are systems that send tens of millions emails using Nodemailer and leaking file descriptors would have been noticed quite fast.

**Comment by sheepa** [comment]
How would you like me to debug it exactly?

**Comment by andris9** [comment]
Just try to figure out what file descriptors these are, where are these coming from (smtp connection? Attachment file?) and why these do not close. The first thing I’d consider is if you provide an attachment by calling fs.createReadStream instead of filename or something like that

**Comment by sheepa** [comment]
I have used strace to track down which file descriptors remain open. It looks like the connection to the sendmail agent remains in half open state. 

connect(78, {sa_family=AF_INET, sin_port=htons(25), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
shutdown(78, SHUT_WR)

The file descriptor, 78 in the case, never gets closed fully and remains in a half open state.

**Comment by andris9** [comment]
Once the message is delivered to server, Nodemailer calls socket.end() [here](https://github.com/nodemailer/nodemailer/blob/170025fa65b3c06ce8d8ca206f38b8c26c55bea8/lib/smtp-connection/index.js#L310) which [by docs](https://nodejs.org/api/net.html#net_socket_end_data_encoding) half-closes the socket. i.e., it sends a FIN packet. Normally the server should close the socket on its side as well, at least that what happens with majority of servers, not sure what is going on with your sendmail.

As a quick fix you could try to use [pooled SMTP](https://nodemailer.com/smtp/pooled/) with `maxMessages` set to `Infinity`. This ensures that messages are delivered over a single (or few) connections instead of opening a new connection for every message.

**Comment by drakedevel** [comment]
@andris9 I just hit this after an upgrade to Node 10.x -- I spent some time tracking it down and I believe the issue is in  `SMTPConnection._onConnect`:

https://github.com/nodemailer/nodemailer/blob/f9b85ac52669fe47dfa44a78b3e5010364916723/lib/smtp-connection/index.js#L685-L689

The `net.Socket` constructor installs handlers for internal events. In Node 9.x, it installs handlers for `'finish'` and `'end'`, and even though `SMTPConnection` blows away the `'end'` handler the rest of the logic is sufficient to prevent a file descriptor leak. 

However, in Node 10.x, there were substantial simplifying changes to `net.Socket`, and now the `'end'` handler is required to actually close the underlying file descriptor (unless you explicitly call `.destroy()`). This sort of potential breakage is probably why the Node docs have had a warning against using `removeAllListeners` on sockets [since Node 0.10.x](https://nodejs.org/docs/latest-v0.10.x/api/events.html#events_emitter_removealllisteners_event) :stuck_out_tongue: 

I don't know for sure why this code was originally added, but I don't think there's any benefit to it for freshly-created sockets, so my best guess is it is needed by the proxy functionality (which I haven't dug into). Perhaps it could work to track the event emitters added by `SMTPConnection` and explicitly `.off` them in `_destroy`?

**Comment by kriddile** [comment]
@andris9 We also just hit this after upgrading to Node 10...kind of a big problem for us...we may have to downgrade Node until this is fixed.

**Comment by avi91** [comment]
Any update on this?
I'm also using nodemailer with Node10 and stuck with the same issue.
Constantly getting 'Too many open files' error, after sending bulk email.

I tried this solution given by @andris9 , but no luck.

> As a quick fix you could try to use pooled SMTP with maxMessages set to Infinity. This ensures that messages are delivered over a single (or few) connections instead of opening a new connection for every message.

**Comment by g41n** [comment]
> Any update on this?
> I'm also using nodemailer with Node10 and stuck with the same issue.
> Constantly getting 'Too many open files' error, after sending bulk email.
> 
> I tried this solution given by @andris9 , but no luck.
> 
> > As a quick fix you could try to use pooled SMTP with maxMessages set to Infinity. This ensures that messages are delivered over a single (or few) connections instead of opening a new connection for every message.

I'm in the same situation.
Why is this topic closed?
Downgrade from Node.js 10.x to 9.x seems working at the moment, but that's not a definitive solution...
