### ISSUE TITLE
addressParser issue - when quotes missing around name separated by comma, address parsed incorrectly

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#973]
When quotes are not found around a name, e.g. mail.from is `'Reinman, Andris <andris.reinman@gmail.com>'` it gets parsed incorrectly as `Reinman` and `Andris <andris.reinman@gmail.com>`. 

Reference & Example:
https://github.com/niftylettuce/forward-email/issues/80#issuecomment-454074942

**Comment by andris9** [comment]
This is by design. Email address lists are comma separated values. Try pasting the same string to the "To" field of some email client, most probably you'd get an error about an invalid email address.

Regarding your linked issue - multiple addresses *are* allowed in From field, so if you have something like this in the header:

```
From: val1, val2 <val2.val1@atos.net>
```

Then it means that there are two authors – a local user called "val1" and someone called "val2" with email address "val2.val1@atos.net".

If you try to send such a message then most probably you get an error, at least gmail responds with something like this:

```
550-5.7.1 [90.190.105.213      13] Messages with multiple addresses in From:
550 5.7.1 header are not accepted. m20-v6si3445402ljg.64 - gsmtp
Connection closed by foreign host.
```
